package com.xframework.boot.ibator.test.mapper;

import com.xframework.boot.ibator.test.entity.SysParam;
import com.xframework.boot.ibator.test.entity.SysParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SysParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    long countByExample(SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    int deleteByExample(SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    int deleteByPrimaryKey(String paramCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    int insert(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    int insertSelective(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    List<SysParam> selectByExampleWithRowbounds(SysParamExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    List<SysParam> selectByExample(SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    SysParam selectByPrimaryKey(String paramCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysParam record, @Param("example") SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    int updateByExample(@Param("record") SysParam record, @Param("example") SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    int updateByPrimaryKeySelective(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    int updateByPrimaryKey(SysParam record);
}