package com.xframework.boot.ibator.test.entity;

import java.io.Serializable;
import lombok.Data;

@Data
public class SysParam implements Serializable {
    /**
     * PARAM_CODE
     */
    private String paramCode;

    /**
     * PARAM_VALUE
     */
    private String paramValue;

    /**
     * PARAM_DESC
     */
    private String paramDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_param
     *
     * @mbg.generated Mon Jan 16 15:00:19 CST 2017
     */
    private static final long serialVersionUID = 1L;
}